### ISSUE TITLE
To Do:

### ISSUE THREAD

**Issue by alnopa9** [dorothealint/William_Combe_Works#15]
- [x] Fix Doctor Syntax footer

- [x] Make top.html navbar sticky

- [x] create Works dropdown menu for navbar

- [x] create Analysis link in navbar

- [x] Fix bug in accordion sidebar for Modern Spectator

- [x] Make navigation sidebar and toggle sidebar for Modern Spectator sticky

- [x] Finish up timeline svg and link to Analysis

- [x] Add repo and site links to xml files (replace target="needed")

- [x] change div elements to span in Modern Spectator to allow for toggle

- [x] Create XSLT to pull the epigraphs and signatures from Modern Spectator (analysis)

- [x] update index.html to reflect actual analysis

- [x] add About Team and About Combe pages

- [x] add Lord Craven and First of April to Works dropdown menu

**Comment by alnopa9** [comment]
@dorothealint , I just made this to organize the little things I have left do on the site. Feel free to add to it if you can think of anything else!

**Comment by dorothealint** [comment]
@alnopa9 We have to tweak that description on the index page because that's not exactly what we are doing in the analysis.  We don't have transcriptions of the original Spectator to compare Combe's to!  I don't think they exist in one place yet either.  Something like:
Plot a timeline of the works of William Combe's life.  What was he working on and when?
What did William Combe read?  A collection of his epigraphs.
The stylometric analysis part is good and would be the analysis on Modern Spectator and the Amelia's Letters is good.

Write an about you!  You get credit for that web design!  People can look back in github and see my original attempt at failure :-)

**Comment by dorothealint** [comment]
@alnopa9 I started the xslt for the signatures!  Pushed it to the repo.  I still have to fix the markup on the 1813 ones and this xslt is in progress but I have a meeting so I pushed it the way it is.

**Comment by alnopa9** [comment]
@dorothealint sounds good! I just finished up the nav bar, now it has the dropdown menus for Works and Analysis. I'm going to get the About Pages up and put in the links and I'll do a rough markup of the other works of his that are on the repo.

**Comment by alnopa9** [comment]
@dorothealint I got the signature xslt to work. I just had to move the .xslt file up one folder for the directory reference you had set in the variable to work. I'm starting on the epigraphs xslt now.

**Comment by alnopa9** [comment]
@dorothealint I have the epigraphs xlst file done and I put an accordion sidebar for the page as well. It is up on the server.

**Comment by alnopa9** [comment]
@dorothealint can you resend that email with the paragraphs you typed up to me? I can't seem to find it.  Can you send it to my gmail? It's argento.alyssa@gmail.com. Thanks!
