### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by alnopa9** [dorothealint/William_Combe_Works#16]
Please leave your feedback for our project here!
Thanks!

**Comment by JustinCampbell9** [comment]
I really like how you can filter and highlight different things in the text as well as the links to allow you to skip through the text via the clickable links. It makes it very easy to navigate. Personally without knowing anything about William Combe it seems like it makes it a lot easier to learn. Also I really like the sticky heading that stays on the page when scrolling down. That's something that I personally couldn't get to work on one of my assignments. 

I guess I'm not one to talk but I wish I would've seen the timeline working with the separate dates with links to each of the publications. This would've made it easy to see when and what he wrote. Other than that I really like the project and other than adding new documents you find it looks very good!

**Comment by alnopa9** [comment]
@JustinCampbell9 I never thought of linking the works to the timeline, but that's a good idea! Originally, the header/navbar was supposed to be sticky, but I was having a difficult time getting it to be in the correct place and not jumping around on the screen. Instead, I simply used a position: fixed statement for the links-container that contains the navbar.

**Comment by Julegirl** [comment]
Your website looks beautiful! I love the graphics that you added onto it. And your links are so well organized. I agree with Justin, it would be nice to see a timeline with separate dates with links. But I think it would have been nice to see a little mark-up; maybe for people, places, or times that were mentioned in the passages. This could also help with future research because the people or places mentioned could help you find more of his works.

**Comment by ebeshero** [comment]
@alnopa9 and @JustinCampbell9 you can totally work links into your SVG in your same XSLT you’re using to make the timeline...We did this on the timeline for the Overholt project last spring—let me hunt up the resources we used. SVG links look a little different from HTML, but it is the same concept...

**Comment by ebeshero** [comment]
@alnopa9 @JustinCampbell9 Here's the timeline from the project last spring: http://overholt.newtfire.org/Timeline.html  
If you view the page source in the browser, you can see the linking code. It's an `<a>` element, but it has a namespaced attribute: `xlink:href="your-link-target-here"` and a little xlink title that goes with it. If you can grab a little info from your source XML file about your entries, and you have predictable filenames on your project website, you can construct those links. Here's some code from Overholt with the link surrounding the SVG element. This is *exactly* what's cool about SVG is you can make the graphics interactive just like text, since the image is XML the whole way down. You can even do show-hide stuff with them with JavaScript.

```

<a xlink:href="Personography.html#AO" xlink:title="View the Personography Entry">
  <text x="200" y="0">Abraham Overholt</text>
 </a>
```

**Comment by bnm29** [comment]
The website for this project looks amazing and is set up in a way that is easy to navigate. The timeline containing dates and attached links was very helpful, as well as the "click to highlight" feature which I found to be very useful. The colors on the website go well together and make things easy on the eyes in terms of reading the material on a screen. I also felt that the "about the team" tab was a good way of introducing and getting to know Dorothea and Alyssa a little bit. The presentation I believe was great and interesting, and a bit funny at times because of the funny comments Dorothea was making. Each of the team members seemed comfortable and enthusiastic about their project, and they both knew about each detail that both members put into the website.

**Comment by BMT45** [comment]
I really enjoy the design of the website.   It makes it easy to view and search through the information on the website.  I’m also a big fan of click to highlight because it reduces the amount of time necessary to find certain information.   Everything on this site works effectively to present the information from their research.
