### ISSUE TITLE
Website work

### ISSUE THREAD

**Issue by dorothealint** [dorothealint/William_Combe_Works#5]
I've just pushed a rough index and css file to the repository.  If either of you want to work on it, feel free to change anything you like!  There is a reason I am not an art student.  I admit my failings in color and design!
I have not put it on the server yet.

@alnopa9 @emb184

**Comment by alnopa9** [comment]
I did a little for the web page on my own, but I can update it so that it resembles your links. I can do the SSI for it, too. The blue at the top can be changed, I just wanted something to make the header stand out. I was looking at the Akira project page and I liked how they had the background set up; the blue and black dotted gradient is static with the black over top that holds the content.
