### ISSUE TITLE
Push Documents

### ISSUE THREAD

**Issue by alnopa9** [dorothealint/William_Combe_Works#9]
Hey Dorothea,
Just a reminder to push you XML markup onto GitHub. I don't work tonight, so I'll have some free time to work on the site layout! 👍
Thanks in advance,
Alyssa!

**Comment by dorothealint** [comment]
Hi Alyssa, @alnopa9 
I pushed some of the magazine column files of Combe.  They do have some dirty code, some of it intentional because when I first transcribed them over the summer, I just put it in to make sure xml would flag some things I wasn't sure how I wanted to mark for analysis.
I also pushed the ODD I started.  It definitely needs some work too.
Dorothea
